// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJR_rFjZ4aN4mHD7yNGQugJwJuANm6fMQ',
    appId: '1:977543887738:web:762f0ba713c5c92dbf74c3',
    messagingSenderId: '977543887738',
    projectId: 'cfinances-3e521',
    authDomain: 'cfinances-3e521.firebaseapp.com',
    storageBucket: 'cfinances-3e521.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXn7L8bvnoNi5Xng1P_nyAdFBDRI-8t6M',
    appId: '1:977543887738:android:75a87b7e3d0c5e05bf74c3',
    messagingSenderId: '977543887738',
    projectId: 'cfinances-3e521',
    storageBucket: 'cfinances-3e521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGT16_fXVu6wy8AMuUxmrAp_gi02K6ZE',
    appId: '1:977543887738:ios:fae959a27f23453cbf74c3',
    messagingSenderId: '977543887738',
    projectId: 'cfinances-3e521',
    storageBucket: 'cfinances-3e521.appspot.com',
    iosBundleId: 'com.example.financesApp',
  );
}
